version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "piggybank-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1c5byjzodetti"
s3_prefix = "piggybank-api"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "NetworkStackName=\"network-stack\""
image_repositories = []
